language: julia

os:
  - linux
  - osx

arch:
  - x64
  - amd64
  # - ppc64le
  - arm64

julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y gfortran;
      sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib;
    else
      brew update;
    fi
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

after_success:
  - julia -e 'if Sys.islinux() && string(VERSION)[1:3] == "1.3"
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    else
      println("Coverage skipped")
    end'
