language: julia

os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - 0.6

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -y gfortran libblas-dev liblapack-dev;
      sudo ln -s /usr/lib/gcc/x86_64-linux-gnu/$(gfortran -dumpversion | cut -f1,2 -d.)/libgfortran.so /usr/local/lib;
    else
      brew install gcc;
    fi

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("PROPACK"); Pkg.test("PROPACK"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("PROPACK")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
