language: julia

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - amd64
  # - ppc64le
  - arm64

julia:
  - 1.3
  - 1.4
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

after_success:
  - julia -e 'if Sys.islinux() && string(VERSION)[1:3] == "1.4"
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    else
      println("Coverage skipped")
    end'
